name       : haskell-call-stack
version    : 0.1.0
release    : 3
source     :
    - http://hackage.haskell.org/package/call-stack-0.1.0/call-stack-0.1.0.tar.gz : f25f5e0992a39371079cc25c2a14b5abb872fa7d868a32753aac3a258b83b1e2
license    : MIT
component  : programming.haskell
summary    : Use GHC call-stacks in a backward compatible way
description: |
    Use GHC call-stacks in a backward compatible way
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
