name       : haskell-call-stack
version    : 0.2.0
release    : 4
source     :
    - https://hackage.haskell.org/package/call-stack-0.2.0/call-stack-0.2.0.tar.gz : 95c693c93958758d714dee22edc56d4ebb2dcefa4412264e941e32ccd6e4e0c7
license    : MIT
component  : programming.haskell
summary    : Use GHC call-stacks in a backward compatible way
description: |
    Use GHC call-stacks in a backward compatible way
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
